import { Effect, Redacted, Schema } from "effect";
import { makeRequest } from "../make-request";
import { resolveMerchantAccessToken } from "../auth";

// Clover returns monetary/quantity values as either JSON numbers or strings in
// cents (e.g. `"price": "1000"`), so decode tolerates both and lands as a number.
const CloverNumber = Schema.Union(Schema.Number, Schema.NumberFromString);

const CloverReference = Schema.Struct({ id: Schema.String });

/**
 * The disposition Clover reports for a payment attempt. This is the full set of
 * values from Clover's autogenerated `Result` enum
 * (`com.clover.sdk.v3.payments.Result` in clover-android-sdk). It is a strict
 * literal so an unexpected/new value fails decode loudly.
 */
export const CloverPaymentResultSchema = Schema.Literal(
  "SUCCESS",
  "FAIL",
  "INITIATED",
  "VOIDED",
  "VOIDING",
  "VOID_FAILED",
  "AUTH",
  "AUTH_COMPLETED",
  "DISCOUNT",
  "OFFLINE_RETRYING",
  "PENDING",
);

export type CloverPaymentResult = typeof CloverPaymentResultSchema.Type;

export const CloverOrderPaymentStateSchema = Schema.Literal(
  "PAID",
  "OPEN",
  "PARTIALLY_PAID",
  "REFUNDED",
  "PARTIALLY_REFUNDED",
);

export type CloverOrderPaymentState = typeof CloverOrderPaymentStateSchema.Type;

// A line item may carry zero or more percentage/amount discounts. Clover stores
// `amount` as a non-positive integer (a reduction), and expresses percentages
// either as whole `percentage` or `percentageDecimal` (percent × 10000).
const CloverDiscountSchema = Schema.Struct({
  amount: Schema.optional(CloverNumber),
  percentage: Schema.optional(CloverNumber),
  percentageDecimal: Schema.optional(CloverNumber),
});

export const CloverOrderLineItemSchema = Schema.Struct({
  id: Schema.String,
  name: Schema.optional(Schema.String),
  // Per-unit price in cents. For PER_UNIT (weighted) items the extended amount is
  // `price * unitQty / 1000`; for per-each items it is the amount for one unit.
  price: Schema.optional(CloverNumber),
  // Reference to the inventory item this line sold. Its `id` is the Clover item
  // id used to resolve the vendor (`vendor_items.clover_item_id`). Absent for
  // custom/manually-keyed line items.
  item: Schema.optional(CloverReference),
  // Fixed-point quantity (thousandths) for PER_UNIT items only.
  unitQty: Schema.optional(CloverNumber),
  exchanged: Schema.optional(Schema.Boolean),
  refunded: Schema.optional(Schema.Boolean),
  discounts: Schema.optional(
    Schema.Struct({
      elements: Schema.optional(Schema.Array(CloverDiscountSchema)),
    }),
  ),
});

export type CloverOrderLineItem = typeof CloverOrderLineItemSchema.Type;

export const CloverOrderPaymentSchema = Schema.Struct({
  id: Schema.String,
  amount: CloverNumber,
  tipAmount: Schema.optional(CloverNumber),
  taxAmount: Schema.optional(CloverNumber),
  result: CloverPaymentResultSchema,
  createdTime: Schema.optional(CloverNumber),
});

export type CloverOrderPayment = typeof CloverOrderPaymentSchema.Type;

export const CloverOrderSchema = Schema.Struct({
  id: Schema.String,
  total: Schema.optional(CloverNumber),
  paymentState: CloverOrderPaymentStateSchema,
  state: Schema.optional(Schema.String),
  createdTime: CloverNumber,
  modifiedTime: CloverNumber,
  lineItems: Schema.optional(
    Schema.Struct({
      elements: Schema.optional(Schema.Array(CloverOrderLineItemSchema)),
    }),
  ),
  payments: Schema.optional(
    Schema.Struct({
      elements: Schema.optional(Schema.Array(CloverOrderPaymentSchema)),
    }),
  ),
});

export type CloverOrder = typeof CloverOrderSchema.Type;

export const CloverOrderListSchema = Schema.Struct({
  elements: Schema.Array(CloverOrderSchema),
  href: Schema.optional(Schema.String),
});

export type CloverOrderList = typeof CloverOrderListSchema.Type;

/**
 * Fetches a single order with its line items and payments expanded.
 *
 * Line items and payments are expandable collections on the order, so
 * `expand=lineItems,payments` is
 * always requested. This requires the merchant token to hold the **Read order**
 * permission; a token without it is rejected by Clover with a `403`.
 */
export function getCloverOrder(merchantId: string, orderId: string) {
  return Effect.gen(function* () {
    const redactedToken = yield* resolveMerchantAccessToken(merchantId);
    const accessToken = Redacted.value(redactedToken);

    return yield* makeRequest({
      method: "GET",
      path: `/v3/merchants/${merchantId}/orders/${orderId}`,
      accessToken,
      responseSchema: CloverOrderSchema,
      urlParams: { expand: "lineItems,payments" },
    });
  });
}

/**
 * Lists a page of orders for the merchant.
 *
 * `filter` is a Clover query filter (e.g. `modifiedTime>=1700000000000`).
 * `orderBy` is a Clover sort spec (e.g. `modifiedTime ASC`).
 */
export function listCloverOrders(
  merchantId: string,
  options?: {
    readonly limit?: number;
    readonly offset?: number;
    readonly filter?: string;
    readonly orderBy?: string;
    readonly expand?: string;
  },
) {
  return Effect.gen(function* () {
    const redactedToken = yield* resolveMerchantAccessToken(merchantId);
    const accessToken = Redacted.value(redactedToken);

    const urlParams: Record<string, string> = {
      expand: options?.expand ?? "payments,lineItems",
    };
    if (options?.limit !== undefined) {
      urlParams.limit = String(options.limit);
    }
    if (options?.offset !== undefined) {
      urlParams.offset = String(options.offset);
    }
    if (options?.filter !== undefined) {
      urlParams.filter = options.filter;
    }
    if (options?.orderBy !== undefined) {
      urlParams.orderBy = options.orderBy;
    }

    return yield* makeRequest({
      method: "GET",
      path: `/v3/merchants/${merchantId}/orders`,
      accessToken,
      responseSchema: CloverOrderListSchema,
      urlParams,
    });
  });
}
