import { Effect, Redacted, Schema } from "effect";
import { makeRequest } from "../make-request";
import { resolveMerchantAccessToken } from "../auth";

/**
 * The disposition Clover reports for a payment attempt. This is the full set of
 * values from Clover's autogenerated `Result` enum
 * (`com.clover.sdk.v3.payments.Result` in clover-android-sdk). It is a strict
 * literal — an unexpected/new value fails decode loudly rather than slipping
 * through as an opaque string — and is normalized to the sale's `paymentStatus`
 * at the drain boundary.
 */
export const CloverPaymentResultSchema = Schema.Literal(
  "SUCCESS",
  "FAIL",
  "INITIATED",
  "VOIDED",
  "VOIDING",
  "VOID_FAILED",
  "AUTH",
  "AUTH_COMPLETED",
  "DISCOUNT",
  "OFFLINE_RETRYING",
  "PENDING",
);

export type CloverPaymentResult = typeof CloverPaymentResultSchema.Type;

export const CloverPaymentSchema = Schema.Struct({
  id: Schema.String,
  amount: Schema.Number,
  taxAmount: Schema.optional(Schema.Number),
  discountAmount: Schema.optional(Schema.Number),
  createdTime: Schema.Number,
  // Clover's disposition for the payment attempt. Required and typed as the full
  // set of Clover `Result` values (see CloverPaymentResultSchema) so every
  // payment is ingested with a known outcome and normalized downstream, rather
  // than dropped. The drain maps this to the sale's `paymentStatus`.
  result: CloverPaymentResultSchema,
  // A payment carries no line items of its own — only a reference to the order it
  // paid. Line items live on that order and are fetched separately via
  // `getCloverOrder` (see resources/orders.ts). `order` can be absent for
  // payments not tied to an order (e.g. some manual/standalone transactions).
  order: Schema.optional(Schema.Struct({ id: Schema.String })),
});

export type CloverPayment = typeof CloverPaymentSchema.Type;

export const CloverPaymentListSchema = Schema.Struct({
  elements: Schema.Array(CloverPaymentSchema),
  href: Schema.optional(Schema.String),
});

export type CloverPaymentList = typeof CloverPaymentListSchema.Type;

export function getCloverPayment(merchantId: string, paymentId: string) {
  return Effect.gen(function* () {
    const redactedToken = yield* resolveMerchantAccessToken(merchantId);
    const accessToken = Redacted.value(redactedToken);

    return yield* makeRequest({
      method: "GET",
      path: `/v3/merchants/${merchantId}/payments/${paymentId}`,
      accessToken,
      responseSchema: CloverPaymentSchema,
    });
  });
}

/**
 * Lists a page of payments for the merchant, most useful with a static access
 * token to pull recent payments directly from the Clover API.
 *
 * `filter` is a Clover query filter (e.g. `createdTime>=1700000000000`).
 * `orderBy` is a Clover sort spec (e.g. `createdTime ASC`).
 *
 * `expand` requests Clover expandable fields (e.g. `"lineItems"`). It is **not**
 * requested by default: expanding line items requires order/line-item read
 * permission, and a payments-only token responds `403 Invalid permissions for
 * expandable fields`. The importer only needs each payment's id/created time, so
 * it omits `expand`; pass it explicitly only when the token is scoped for it.
 */
export function listCloverPayments(
  merchantId: string,
  options?: {
    readonly limit?: number;
    readonly offset?: number;
    readonly filter?: string;
    readonly orderBy?: string;
    readonly expand?: string;
  },
) {
  return Effect.gen(function* () {
    const redactedToken = yield* resolveMerchantAccessToken(merchantId);
    const accessToken = Redacted.value(redactedToken);

    const urlParams: Record<string, string> = {};
    if (options?.limit !== undefined) {
      urlParams.limit = String(options.limit);
    }
    if (options?.offset !== undefined) {
      urlParams.offset = String(options.offset);
    }
    if (options?.filter !== undefined) {
      urlParams.filter = options.filter;
    }
    if (options?.orderBy !== undefined) {
      urlParams.orderBy = options.orderBy;
    }
    if (options?.expand !== undefined) {
      urlParams.expand = options.expand;
    }

    return yield* makeRequest({
      method: "GET",
      path: `/v3/merchants/${merchantId}/payments`,
      accessToken,
      responseSchema: CloverPaymentListSchema,
      urlParams,
    });
  });
}
